name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Build Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker build -t your-registry/your-app:${{ github.sha }} .
          docker build -t your-registry/your-app:latest .

    # Uncomment and modify these steps if you want to push to a registry
    # - name: Login to Docker Registry
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   uses: docker/login-action@v2
    #   with:
    #     registry: your-registry
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: |
    #     docker push your-registry/your-app:${{ github.sha }}
    #     docker push your-registry/your-app:latest
